# Site settings
title: Galena Lumen
email: galena.lumen@protonmail.com
subtitle: >
  El que sabe no habla, el que habla no sabe - Lao Tzu
description: >
  Filosofía, economía, política, lo que sea.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://galena-lumen.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
markdown: rdiscount
permalink: pretty
