# Site settings
title: Galena Lumen
email: galena.lumen@inbox.com
description: > # this means to ignore newlines until "baseurl:"
  Philosophy, economics, politics, whatever.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://galena-lumen.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
markdown: rdiscount
permalink: pretty
