# Site settings
title: Galena Lumen
email: galena.lumen@protonmail.ch
subtitle: >
  Strictly speaking, God does not love or hate - Baruch Spinoza
description: >
  Philosophy and emergence.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://galena-lumen.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
markdown: rdiscount
permalink: pretty
